[package]
name = "funding-features"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
funding-core = { path = "../funding-core" }
md-core = { path = "../md-core" }
num-bigint = "0.4.6"
num-traits = "0.2.19"
ring = "0.17"
uuid = "1.24.1"
